### ISSUE TITLE
False positives - flat trajectories?

### ISSUE THREAD

**Issue by carolbarata** [mrborges23/Bait-ER#3]
Bait-ER sigmas on the Barghi et al (2019) dataset of D. simulans pops adapted to new temp environment indicate there are 'islands' of high sigma across the genome.
I have attached a subset of those 'island'-trajectories in sync format for the X chromosome (|sigma| > 0.25).
Plotted approx. 10% of randomly sampled trajectories and they seem to be consistently flat across replicate pops. This suggests Bait-ER is overestimating sigma for some of these flat trajectories which have high (or low if you consider the alternative allele) starting frequency.
Perhaps worth considering adding a filtering step to the data input depending on the trajectory shape or on the initial frequency?
[Dsim_F0-F60_Q20_polymorphic_CMH_FET_blockID_X_highvar_subset_sorted.sync.zip](https://github.com/mrborges23/Bait-ER/files/4495087/Dsim_F0-F60_Q20_polymorphic_CMH_FET_blockID_X_highvar_subset_sorted.sync.zip)

**Comment by mrborges23** [comment]
We added a filtering step for the trajectories variance. Flat trajectories have tiny variances (<0.01) and cannot be used for inference.
